### ISSUE TITLE
Filter displaying the wrong tasks

### ISSUE THREAD

**Issue by tenbob** [QTodoTxt/QTodoTxt2#101] opened 2018-05-18 04:00 UTC
I'm a new user of QTodoTxt2 on Windows 7. I've been getting a weird problem where the list of tasks contains all the wrong items. For example, in the filter pane on the left it says there are 8 tasks with priority (B). When I click on that item, the task pane displays 8 tasks. But they are NOT the ones with priority (B). They are random tasks from my list with no obvious pattern. 

A similar thing happens when I click each item in the filter tree. The task pane contains the correct number of tasks, but they are all the wrong ones.

This is my setup. I installed Python 3.6.5 64 bit from the official site. I also installed PyQt5. I downloaded QTodoTxt2-master.zip 547e63e from Github and unzipped it to its own folder. I executed the program from the command line with 

`python \path\to\qtodotxt.pyw`

I can see a number of error messages in the command window which may relate to this. Every time I click one of the filter items I see the message 

`filteredTasks about to change in python`
`qml: TableViewSelection: index out of range`

At the moment the program is unusable for me. Could you please investigate.

**Comment by Nelvin** [comment] 2018-05-29 09:19
Same issue here, using 32bit Python 3.65 and PyQt5 (installed using pip)

**Comment by oroulet** [comment] 2018-05-29 09:38
Looks like filtering is broken. I have no time to look at it for now

**Comment by Nelvin** [comment] 2018-05-29 09:56
I did have a quick look at it - the filtering by itself seems to work (I just dumped the resulting tasklists in filter_controller.filterTasks() to a console window and this completely differs from the tasks shown in the listview), so I guess it's a kind of synchronization issue between the gui and the filtered tasklist.
Sadly I have no experience using Qt/PyQt/QML so I have no idea how the listview of the tasks is updated and what the issue might be.

**Comment by Nelvin** [comment] 2018-05-30 17:07
Is there an easy way to see how the UI is wired? I installed the pyqt tools so I have the qtdesigner but it seems I need a .ui file and there is none in the project.
What would be required to try to fix this issue?

**Comment by oroulet** [comment] 2018-06-16 10:32
jsut had short look now. I confirm the bug. This definitely used to work. must have been some changes in qt...

**Comment by oroulet** [comment] 2018-06-16 10:39
I have not lookes at that code for a very long time. it looks lie there is a signal filteredTasksChanged which is emited every time the list changed line 203 in main_controller.py.

**Comment by oroulet** [comment] 2018-06-16 17:32
just now I got in fact an even worth result, without filtering the display of task became random....

**Comment by tenbob** [comment] 2018-06-18 09:41
I'm having trouble understanding the mechanism for signals and slots. But here is a suggestion to try. I am unable to code it properly myself. 

I think what is missing is a message to the model that the data has changed. This should sent by executing `endResetModel()`. There are various private messages and signals going on, but nothing is telling the model directly. 

To test this theory we need to execute `endResetModel()` manually. Maybe someone who is better at coding than me could write a test routine that executes it when you press a key. Then we could see if the data in the GUI updates.

Just a suggestion. I may be completely wrong.

**Comment by oroulet** [comment] 2018-06-18 09:48
the problem is that the data updates...it just updates to something random... it really looks like a bug in qt triggered by something in our design... but our design has nothing special....

**Comment by tenbob** [comment] 2018-06-18 13:45
OK. I will leave it with you.

**Comment by oroulet** [comment] 2018-06-19 06:37
@tenbob do not give up. This is a very good way to learn things ;-) and  I am currently not using this program so it is a bad idea to rely on me...

**Comment by FakeNameSE** [comment] 2018-07-25 06:11
I just wanted to let you know that I am still running into this problem.

**Comment by topas-rec** [comment] 2019-03-11 06:58
Should be fixed with #122 and in QTodoTxt2 version 2.0.1

**Closed by topas-rec** 2019-03-11 06:58 UTC
